title: "Tech by Jenish"
description: "System Design • AWS • Cloud Architecture • SWE Intern @ Dell • Ex-Adobe • 3x AWS Certified"

url: "https://jenishk20.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Jenish Kothari"
  avatar: "/assets/images/profile.png"
  bio: "SWE Intern @ Dell • Ex Adobe SWE Intern • 3× AWS Certified • System Design & Cloud Engineer"
  location: "Boston, MA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jenishk20"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/jenishkothari"
